#!C:\Users\asmab\OneDrive\Bureau\ESGI_S2\DRL\Exemple_structure_projet\drl_sample_project_python\env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
